(require :conf.pkgs.cmp)

(require :conf.pkgs.null-ls)
(require :conf.pkgs.lspconfig)
(require :conf.pkgs.treesitter)
(require :conf.pkgs.conjure)
(require :conf.pkgs.test)
(require :conf.pkgs.trouble)
(require :conf.pkgs.lsp_lines)
(require :conf.pkgs.dap)
